language: node_js
node_js:
  - "6"
  - "7"
before_script:
  - npm install -g mocha
  - npm install -g eslint
  - npm install -g istanbul
  - npm install -g codecov
script:
  - bash script/ci.sh
after_script:
  - npm run cov
  - codecov